<a href="https://colab.research.google.com/github/tommypolpo/geron-hands_on_ML/blob/main/ch14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Shakespeare Training Dataset

In [1]:
from pathlib import Path
import urllib.request

def download_shkespeare_text():
  path = Path("datasets/shakespeare/shakespeare.txt")
  if not path.is_file():
    path.parent.mkdir(parents=True, exist_ok=True)
    url = "https://homl.info/shakespeare"
    urllib.request.urlretrieve(url, path)
  return path.read_text()

shakespeare_text = download_shkespeare_text()


In [2]:
print(shakespeare_text[:80])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.


In [3]:
len(shakespeare_text)

1115394

In [4]:
type(shakespeare_text)

str

In [5]:
# find the characters used in the text
vocab = sorted(set(shakespeare_text.lower()))
print(vocab)

['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [6]:
"".join(vocab) # this is just to visualize them "closer together"

"\n !$&',-.3:;?abcdefghijklmnopqrstuvwxyz"

In [7]:
# We now create the two translation dictionaries
char_to_id = {char:index for index, char in enumerate(vocab)}
id_to_char = {index:char for index, char in enumerate(vocab)}


In [8]:
# two helper functions to encode text to tensors of token IDs
import torch

def encode_text(text):
  return torch.tensor([char_to_id[char] for char in text.lower()])

def decode_text(char_ids):
  return "".join([id_to_char[char_id.item()] for char_id in char_ids])

In [9]:
encoded = encode_text("Hello, world!")
encoded


tensor([20, 17, 24, 24, 27,  6,  1, 35, 27, 30, 24, 16,  2])

In [10]:
decode_text(encoded)

'hello, world!'

### CharDataset Class

In [11]:
from torch.utils.data import Dataset, DataLoader

class CharDataset(Dataset):
  def __init__(self, text, window_length):
    self.encoded_text =  encode_text(text)
    self.window_length = window_length

  def __len__(self): # how many valids windows
    return len(self.encoded_text) - self.window_length

  # this takes an id as argument and returns the
  # corresponding training window and target (=window shifted by 1)
  def __getitem__(self, idx):
    if idx >= len(self):
      raise IndexError("dataset index out of range")
    end = idx + self.window_length
    window = self.encoded_text[idx:end]
    target = self.encoded_text[idx+1:end+1]
    return window, target

### DataLoaders

In [12]:
window_length = 50
batch_size = 64

train_set = CharDataset(shakespeare_text[:1_000_000], window_length)
valid_set = CharDataset(shakespeare_text[1_000_000:1_060_000], window_length)
test_set = CharDataset(shakespeare_text[1_060_000:], window_length)


train_loader = DataLoader(train_set, batch_size, shuffle=True)
valid_loader = DataLoader(valid_set, batch_size)
test_loader = DataLoader(test_set, batch_size)

##Evaluation and Training Functions

In [13]:
%pip install -q torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 40.5 MB/s eta 0:00:00


In [14]:
import torchmetrics

def evaluate_tm(model, data_loader, metric):
    model.eval()
    metric.reset()
    with torch.no_grad():
        for X_batch, y_batch in data_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            metric.update(y_pred, y_batch)
    return metric.compute()

def train(model, optimizer, loss_fn, metric, train_loader, valid_loader,
          n_epochs, patience=2, factor=0.5, epoch_callback=None):
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="max", patience=patience, factor=factor)
    history = {"train_losses": [], "train_metrics": [], "valid_metrics": []}
    for epoch in range(n_epochs):
        total_loss = 0.0
        metric.reset()
        model.train()
        if epoch_callback is not None:
            epoch_callback(model, epoch)
        for index, (X_batch, y_batch) in enumerate(train_loader):
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            loss = loss_fn(y_pred, y_batch)
            total_loss += loss.item()
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
            metric.update(y_pred, y_batch)
            train_metric = metric.compute().item()
            print(f"\rBatch {index + 1}/{len(train_loader)}", end="")
            print(f", loss={total_loss/(index+1):.4f}", end="")
            print(f", {train_metric=:.2%}", end="")
        history["train_losses"].append(total_loss / len(train_loader))
        history["train_metrics"].append(train_metric)
        val_metric = evaluate_tm(model, valid_loader, metric).item()
        history["valid_metrics"].append(val_metric)
        scheduler.step(val_metric)
        print(f"\rEpoch {epoch + 1}/{n_epochs},                      "
              f"train loss: {history['train_losses'][-1]:.4f}, "
              f"train metric: {history['train_metrics'][-1]:.2%}, "
              f"valid metric: {history['valid_metrics'][-1]:.2%}")
    return history

## Char-RNN Model

In [15]:
if torch.cuda.is_available():
  device = "cuda"
else:
  device = "cpu"

In [16]:
import torch.nn as nn
class ShakespeareModel(nn.Module):
    def __init__(self, vocab_size, n_layers=2, embed_dim=10, hidden_dim=128,
                 dropout=0.1):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, embed_dim)
        self.gru = nn.GRU(embed_dim, hidden_dim, num_layers=n_layers,
                          batch_first=True, dropout=dropout)
        self.output = nn.Linear(hidden_dim, vocab_size)

    def forward(self, X):
        embeddings = self.embed(X)
        outputs, _states = self.gru(embeddings)
        return self.output(outputs).permute(0, 2, 1)

torch.manual_seed(42)
model = ShakespeareModel(len(vocab)).to(device)

### Training

In [17]:
n_epochs = 2
xentropy = nn.CrossEntropyLoss()
optimizer = torch.optim.NAdam(model.parameters())
accuracy = torchmetrics.Accuracy(task="multiclass",
                                 num_classes=len(vocab)).to(device)

history = train(model, optimizer, xentropy, accuracy, train_loader, valid_loader,
                n_epochs)

Epoch 1/2,                      train loss: 1.4404, train metric: 55.25%, valid metric: 54.41%
Epoch 2/2,                      train loss: 1.3637, train metric: 57.12%, valid metric: 54.60%


In [18]:
torch.save(model.state_dict(), "my_shakespeare_model.pt")

### Prediction

In [19]:
model.eval()
text = "To be or not to b"
encoded_text = encode_text(text).unsqueeze(dim=0).to(device) # so now it has shape [1,18]

with torch.no_grad():
  Y_logits = model(encoded_text)
  predicted_char_id = Y_logits[0, :, -1].argmax().item() #largest logit of the last prediction: the next letter
  predicted_char = id_to_char[predicted_char_id]
  print(predicted_char) # correctly predict "e"!

e


## Fake Shakesperean Text

In [20]:
# how to use the torch.multinomial function to sample indices
torch.manual_seed(42)
probs = torch.tensor([[0.5, 0.4, 0.1]])
samples = torch.multinomial(probs, replacement = True, num_samples =10)
# replacement = True : allows the same index to be sampled more than once
samples

tensor([[0, 0, 0, 0, 1, 0, 2, 2, 0, 0]])

### Next Char function

In [21]:
import torch.nn.functional as F

# this function samples the character after "text" according to the probability
# predicted by the model (instead of argmax)
def next_char(model, text, temperature = 1):
  encoded_text = encode_text(text).unsqueeze(dim=0).to(device)
  with torch.no_grad():
    Y_logits = model(encoded_text)
    Y_probas= F.softmax(Y_logits[0,:,-1] / temperature, dim =-1)
    predicted_char_id = torch.multinomial(Y_probas, num_samples = 1).item()
    return id_to_char[predicted_char_id]


In [22]:
# this function repeatedly calls next_char

def extend_text(model, text, n_chars=300, temperature =1):
  for _ in range(n_chars):
    text += next_char(model, text, temperature)
  return text

In [23]:
# we can now generate text!

print(extend_text(model, "Ciao", temperature = 100))

Ciaojf3h :c;rjxfndp'cdt-!f
'eyouw xr3dozdcu,xy:utgj,p!hyzdkpxep-nas3fklr,oec3cbmieitp$yacd.r3pgauypj.wgitcea;,qk?tj
jr.$peixhk&bnecf;'onifi'&ytsy&3u.hdhfmb,dzmovfe:mhf:my:r,k;s-h cqvvnfnfsut&-oq'ryoeen?x-hp:d,y&wv f3,dzrdzj-pilv?xpzh,fborp;'?$u;-dd?f-vkinst$;gd$bdg:on-;!wop;w- oechr?no$tenv;-o$;uqo
r:$l


## Sentiment Analysis: IMDB

### IMDB dataset

In [24]:
# see my bear note on how to Hugging Face dataset library
from datasets import load_dataset

imbd_dataset = load_dataset("stanfordnlp/imdb")
split = imbd_dataset["train"].train_test_split(train_size=0.8)

imdb_train_set, imdb_valid_set = split["train"], split["test"]
imdb_test_set = imbd_dataset["test"]


README.md:   0%|          | 0.00/7.81k [00:00<?, ?B/s]

plain_text/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 21.0MB            

plain_text/train-00000-of-00001.parquet: downloading bytes:           |  0.00B            

plain_text/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 20.5MB            

plain_text/test-00000-of-00001.parquet: downloading bytes:           |  0.00B            

plain_text/unsupervised-00000-of-00001.p(…): reconstructing file:   0%|          |  0.00B / 42.0MB            

plain_text/unsupervised-00000-of-00001.p(…): downloading bytes:           |  0.00B            

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

In [25]:
imdb_train_set[1]["text"] #different from Geron's book

'In late 1800s San Francisco, poor well-dressed Errol Flynn (as James J. Corbett) works at a bank, and enjoys attending local "fights" (boxing) with co-worker and drinking buddy Jack Carson (as Walter Lowrie). One day, pretty Alexis Smith (as Victoria Ware) walks into the "Comstock Bank", where Mr. Flynn works. Flynn is so taken with Ms. Smith\'s elegant beauty, he offers to carry her withdrawal purse. Smith is secretly taken with the handsome Flynn, but is put off by his brashness.<br /><br />Flynn\'s good deed (actually, pick-up attempt) gets him a complimentary membership in the snooty "Olympic Club", which conveniently includes a gymnasium (with boxing equipment). However, Flynn\'s presumptuous manner, and practical joking (he tickles men on the parallel bars) irritates "Club" members. When an English boxing champ visits the club, members endeavor to get Flynn to fight the man. They are hopeful Flynn will resign, humiliated by his defeat - but, Flynn wins! <br /><br />First time pr

In [26]:
imdb_train_set[1]["label"]

1

### Tokenizer based on the BPE model

In [27]:
import tokenizers

bpe_model = tokenizers.models.BPE(unk_token="<unk>")
bpe_tokenizer = tokenizers.Tokenizer(bpe_model) #create a tokenizer based on the BPE model
bpe_tokenizer.pre_tokenizer = tokenizers.pre_tokenizers.Whitespace()
special_tokens = ["<pad>", "<unk>"]
bpe_trainer = tokenizers.trainers.BpeTrainer(vocab_size=1000,
                                             special_tokens=special_tokens)

#create a list of all the text in the IMDB dataset
train_reviews = [review["text"].lower() for review in imdb_train_set]

#train the tokenizer on this list
bpe_tokenizer.train_from_iterator(train_reviews, bpe_trainer)


In [28]:
# let us tokenize some text
some_review = "the movies was great and awesome! 😊"
bpe_encoding = bpe_tokenizer.encode(some_review)
bpe_encoding


Encoding(num_tokens=10, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])

In [29]:
bpe_encoding.tokens

['the', 'movies', 'was', 'great', 'and', 'aw', 'es', 'ome', '!', '<unk>']

In [30]:
bpe_token_ids = bpe_encoding.ids
bpe_token_ids

[137, 468, 192, 405, 152, 370, 148, 223, 3, 1]

In [31]:
bpe_tokenizer.decode(bpe_token_ids)


'the movies was great and aw es ome !'

In [32]:
# to create a single tensor containing all the tokens of multiple reviews
# they must be all of the same length: max_lenght + padding
bpe_tokenizer.enable_padding(pad_id=0, pad_token="<pad>")
bpe_tokenizer.enable_truncation(max_length=500)

In [33]:
# we encode 3 reviews at once:
bpe_encodings = bpe_tokenizer.encode_batch(train_reviews[:3])
bpe_batch_ids = torch.tensor([encoding.ids for encoding in bpe_encodings])
bpe_batch_ids

tensor([[ 49, 189, 922,  ...,   0,   0,   0],
        [136,  52, 314,  ...,  14, 172, 350],
        [137, 162,  47,  ...,   0,   0,   0]])

In [34]:
# attention mask tells us where there is no padding
attention_mask = torch.tensor([encoding.attention_mask for encoding in bpe_encodings])
attention_mask

tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0]])

In [35]:
lengths = attention_mask.sum(dim=-1)
lengths

tensor([463, 500, 455])

### Pretrained Tokenizers

#### GPT2 tokenizer

In [36]:
# Let's dowload the pretrained BBPE tokenizer used by the GPT-2 model
import transformers

gpt2_tokenizer = transformers.AutoTokenizer.from_pretrained("gpt2")

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [37]:
gpt2_encoding = gpt2_tokenizer(train_reviews[:3], truncation=True, max_length=500)

gpt2_token_ids = gpt2_encoding["input_ids"][0][:10]
gpt2_token_ids

[72, 8288, 340, 0, 262, 7110, 373, 7650, 11, 9859]

In [38]:
gpt2_tokenizer.decode(gpt2_token_ids)

'i liked it! the plot was weird, drew'

#### WordPiece / BERT tokenizer

In [39]:
bert_tokenizer = transformers.AutoTokenizer.from_pretrained("bert-base-uncased")

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

### Train a Sentiment Analysis Model

#### DataLoader + Tokenization

In [40]:
# we pass a function to the DataLoader that tokenize, truncate and pad the reviews

def collate_fn(batch, tokenizer = bert_tokenizer):
  reviews = [review["text"] for review in batch]
  labels = [[review["label"]] for review in batch]

  encodings = tokenizer(reviews, padding = True, truncation=True, max_length=200,
                        return_tensors="pt")
  labels = torch.tensor(labels, dtype=torch.float32)
  return encodings, labels

In [41]:
batch_size = 256
imdb_train_loader = DataLoader(imdb_train_set, batch_size=batch_size, collate_fn=collate_fn, shuffle=True)
imdb_valid_loader = DataLoader(imdb_valid_set, batch_size=batch_size, collate_fn=collate_fn)
imdb_test_loader = DataLoader(imdb_test_set, batch_size=batch_size, collate_fn=collate_fn)

#### Sentiment Analysis Model

In [42]:
class SentimentAnalysisModel(nn.Module):
    def __init__(self, vocab_size, n_layers=2, embed_dim=128, hidden_dim=64,
                 pad_id=0, dropout=0.2):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, embed_dim,
                                  padding_idx=pad_id)
        self.gru = nn.GRU(embed_dim, hidden_dim, num_layers=n_layers,
                          batch_first=True, dropout=dropout)
        self.output = nn.Linear(hidden_dim, 1)

    def forward(self, encodings):
        embeddings = self.embed(encodings["input_ids"])
        _outputs, hidden_states = self.gru(embeddings)
        return self.output(hidden_states[-1])

In [43]:
torch.manual_seed(42)

vocab_size = bert_tokenizer.vocab_size # how many different tokens!
imdb_model_ps = SentimentAnalysisModel(vocab_size).to(device)

n_epochs = 5
xentropy = nn.BCEWithLogitsLoss()
optimizer = torch.optim.NAdam(imdb_model_ps.parameters())
accuracy = torchmetrics.Accuracy(task="binary").to(device)

history = train(imdb_model_ps, optimizer, xentropy, accuracy,
                imdb_train_loader, imdb_valid_loader, n_epochs)

Epoch 1/5,                      train loss: 0.6896, train metric: 53.26%, valid metric: 56.24%
Batch 76/79, loss=0.6521, train_metric=62.66%

KeyboardInterrupt: 

#### Bidirectional model

In [ ]:
# Let's used packed sequences: a special data structure designed for sequences of variable length
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

In [ ]:
class SentimentAnalysisModelBidi(nn.Module):
    def __init__(self, vocab_size, n_layers=2, embed_dim=128,
                 hidden_dim=64, pad_id=0, dropout=0.2):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, embed_dim,
                                  padding_idx=pad_id)
        self.gru = nn.GRU(embed_dim, hidden_dim, num_layers=n_layers,
                          batch_first=True, dropout=dropout, bidirectional=True)  # set bidirectional = true
        self.output = nn.Linear(2 * hidden_dim, 1)                               # the output dimension is now doubles

    def forward(self, encodings):
        embeddings = self.embed(encodings["input_ids"])
        # this is for the packed sequences
        lengths = encodings["attention_mask"].sum(dim=1)
        packed = pack_padded_sequence(embeddings, lengths=lengths.cpu(),
                                    batch_first=True, enforce_sorted=False)
        ####

        _outputs, hidden_states = self.gru(embeddings)
        # we now need to concatenate the the forard output and backward output
        # of the GRU layer, before feeding it to the output layer
        n_dims = self.output.in_features
        top_states = hidden_states[-2:].permute(1, 0, 2).reshape(-1, n_dims)
        # and finally feed it to the output linear layer
        return self.output(top_states)

In [ ]:
torch.manual_seed(42)

vocab_size = bert_tokenizer.vocab_size
imdb_model_bidi = SentimentAnalysisModelBidi(vocab_size).to(device)

n_epochs = 2
xentropy = nn.BCEWithLogitsLoss()
optimizer = torch.optim.NAdam(imdb_model_bidi.parameters())
accuracy = torchmetrics.Accuracy(task="binary").to(device)

history = train(imdb_model_bidi, optimizer, xentropy, accuracy, imdb_train_loader,
                imdb_valid_loader, n_epochs)

#### Pretrained Embeddings

In [ ]:
# Download the pretrained BERT embedding layer
bert_model = transformers.AutoModel.from_pretrained("bert-base-uncased")
bert_model.embeddings.word_embeddings

In [ ]:
# instead of replacing our nn.Embedding layer, we inizialize it with the weights
# of the pretrained embedding layer
# the code is exactly the same except for the initialization of the embedding layer
# freeze = True for the first few epochs, then unfreeze to fine-tune the parameteres
# the argument pretrained_embeddings will be bert_model.embeddings.word_embeddings
class SentimentAnalysisModelPreEmbeds(nn.Module):
    def __init__(self, pretrained_embeddings, n_layers=2, embed_dim=128,
                 hidden_dim=64, pad_id=0, dropout=0.2):
        super().__init__()
        ##### Embedding layer
        weights = pretrained_embeddings.weight.data
        self.embed = nn.Embedding.from_pretrained(weights, freeze=True)
        embed_dim = weights.shape[-1]
        #####
        self.gru = nn.GRU(embed_dim, hidden_dim, num_layers=n_layers,
                          batch_first=True, dropout=dropout, bidirectional=True)  # set bidirectional = true
        self.output = nn.Linear(2 * hidden_dim, 1)                               # the output dimension is now doubles

    def forward(self, encodings):
        embeddings = self.embed(encodings["input_ids"])
        # packed sequence
        lengths = encodings["attention_mask"].sum(dim=1)
        packed = pack_padded_sequence(embeddings, lengths=lengths.cpu(),
                                     batch_first=True, enforce_sorted=False)

        _outputs, hidden_states = self.gru(embeddings)
        # we now need to concatenate the the forard output and backward output
        # of the GRU layer, before feeding it to the output layer
        n_dims = self.output.in_features
        top_states = hidden_states[-2:].permute(1, 0, 2).reshape(-1, n_dims)
        # and finally feed it to the output linear layer
        return self.output(top_states)

In [ ]:
torch.manual_seed(42)

imdb_model_bert_embeds = SentimentAnalysisModelPreEmbeds(
    bert_model.embeddings.word_embeddings).to(device)

n_epochs = 3
xentropy = nn.BCEWithLogitsLoss()
optimizer = torch.optim.NAdam(imdb_model_bert_embeds.parameters())
accuracy = torchmetrics.Accuracy(task="binary").to(device)

history = train(imdb_model_bert_embeds, optimizer, xentropy, accuracy,
                imdb_train_loader, imdb_valid_loader, n_epochs)

#### Pretrained Model: BERT

In [ ]:
# Instead of just using the embedding from the BERT model, we can use
# it as a more powerful context-aware feature extractor:
# The BERT layer produces a context-aware vector, and we train the
# nn.GRU layer on that (we could skip it entirely and let BERT do the sentiment
# analysis, but for didactic reasons we design it like this).

# Note that we don't need the gru layer to be bidirectional because
# the embedding is already contextualised (look ahead too).
class SentimentAnalysisModelBert(nn.Module):
    def __init__(self, n_layers=2, hidden_dim=64, dropout=0.2):
        super().__init__()
        ## BERT layer
        self.bert = transformers.AutoModel.from_pretrained("bert-base-uncased")
        embed_dim = self.bert.config.hidden_size
        ##
        # The input dimension of the gru layer is adapted
        self.gru = nn.GRU(embed_dim, hidden_dim, num_layers=n_layers,
                          batch_first=True, dropout=dropout)
        self.output = nn.Linear(hidden_dim, 1) # it is not bidirectional anymore
        # so no need to double the dimension

    def forward(self, encodings):
        contextualized_embeddings = self.bert(**encodings).last_hidden_state
        lengths = encodings["attention_mask"].sum(dim=1)
        packed = pack_padded_sequence(contextualized_embeddings, lengths=lengths.cpu(),
                                      batch_first=True, enforce_sorted=False)
        _outputs, hidden_states = self.gru(packed)
        return self.output(hidden_states[-1])

In [ ]:
torch.manual_seed(42)

imdb_model_bert = SentimentAnalysisModelBert().to(device)
imdb_model_bert.bert.requires_grad_(False)

n_epochs = 4
xentropy = nn.BCEWithLogitsLoss()
optimizer = torch.optim.NAdam(imdb_model_bert.parameters())
accuracy = torchmetrics.Accuracy(task="binary").to(device)

history = train(imdb_model_bert, optimizer, xentropy, accuracy,
                imdb_train_loader, imdb_valid_loader, n_epochs)

#### Use more BERT: the class embedding

In [ ]:
# Instead of looking at the embdedding of the whole review, we just look at the embedding
# of the [CLS] (class) token: which containes all the importan features of the review
class SentimentAnalysisModelBert2(nn.Module):
    def __init__(self, hidden_dim=64):
        super().__init__()
        self.bert = transformers.AutoModel.from_pretrained("bert-base-uncased")
        # the embedding dimension is still the same (we are considering only one token
        # but th embedding dimension does not change)
        self.output = nn.Linear(self.bert.config.hidden_size, 1)

    def forward(self, encodings):
        bert_output = self.bert(**encodings)
        # just feed the 0th token to the linear layer
        return self.output(bert_output.last_hidden_state[:, 0])

In [ ]:
## in fact, the bert model contains a hidden layer on top of the class embedding
## that we can use with this code
# replace: bert_output.last_hidden_state[:, 0]
# with: bert_output.pooler_output
#
class SentimentAnalysisModelBert3(nn.Module):
    def __init__(self, hidden_dim=64):
        super().__init__()
        self.bert = transformers.AutoModel.from_pretrained("bert-base-uncased")
        self.output = nn.Linear(self.bert.config.hidden_size, 1)

    def forward(self, encodings):
        bert_output = self.bert(**encodings)
        return self.output(bert_output.pooler_output) # only change is here

In [ ]:
# Training: unfreeze the parameters below!
torch.manual_seed(42)

imdb_model_bert3 = SentimentAnalysisModelBert3().to(device)
imdb_model_bert3.bert.requires_grad_(False) # freeze!

n_epochs = 5
xentropy = nn.BCEWithLogitsLoss()
optimizer = torch.optim.NAdam(imdb_model_bert3.parameters())
accuracy = torchmetrics.Accuracy(task="binary").to(device)

history = train(imdb_model_bert3, optimizer, xentropy, accuracy,
                imdb_train_loader, imdb_valid_loader, n_epochs)

In [ ]:
## Unfreeeze the bert parameters!
imdb_model_bert3.bert.pooler.requires_grad_(True)

history = train(imdb_model_bert3, optimizer, xentropy, accuracy,
                imdb_train_loader, imdb_valid_loader, n_epochs)

### Task-Specific Classes

In [44]:
# from transformers import AutoModelForSequenceClassification
# AutoModel with the "bert-base-uncased" will automatically select BertForSequenceClassificatio
from transformers import BertForSequenceClassification

# Warning: the model inside BertForSequenceClassification
# is pretrained, but the classification head is not
# therefore we actually need to train this model! See below how it classifies the review poorly!

torch.manual_seed(42)
bert_for_binary_clf = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased", num_labels=2, dtype=torch.float16).to(device)
    # num_labels =2 because Hugging Face treat binary classidication (e.g good/bad, as in this case)
    # as a multiclass classification with 2 classes

model.safetensors: reconstructing file:   0%|          |  0.00B /  440MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED | 
cls.predictions.transform.dense.weight     | UNEXPECTED | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED | 
cls.predictions.bias                       | UNEXPECTED | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED | 
cls.predictions.transform.dense.bias       | UNEXPECTED | 
cls.seq_relationship.weight                | UNEXPECTED | 
classifier.bias                            | MISSING    | 
classifier.weight                          | MISSING    | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


In [45]:
# this model will output 2 logits
# therefore use softmax to visualize the probabilities and
# nn.CrossEntropyLoss to train it.

# Warning, as mentioned above, the classification head of this model is not trained
# on the IMDB dataset. In fact: look how wrong this classification is:

encoding = bert_tokenizer(["This was a great movie!"])
with torch.no_grad():
    output = bert_for_binary_clf(
        input_ids=torch.tensor(encoding["input_ids"], device=device),
        attention_mask=torch.tensor(encoding["attention_mask"], device=device))

output.logits

tensor([[-0.0120,  0.6304]], device='cuda:0', dtype=torch.float16)

In [46]:
torch.softmax(output.logits, dim=-1)

tensor([[0.3447, 0.6553]], device='cuda:0', dtype=torch.float16)

#### Trainer API
We could use the usual training function to train the model defined above. But the Transformers library containes a Trainer. p.556

In [47]:
# the trainer does not work with DataLoaders but needs the text tokenized
def tokenize_batch(batch):
    return bert_tokenizer(batch["text"], truncation=True, max_length=200)

tok_imdb_train_set = imdb_train_set.map(tokenize_batch, batched=True)
tok_imdb_valid_set = imdb_valid_set.map(tokenize_batch, batched=True)
tok_imdb_test_set = imdb_test_set.map(tokenize_batch, batched=True)

Map:   0%|          | 0/20000 [00:00<?, ? examples/s]

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

In [48]:
def compute_accuracy(pred):
    return {"accuracy": (pred.label_ids == pred.predictions.argmax(-1)).mean()}

In [49]:
#Tranining configuration: the TrainingArguments object
from transformers import TrainingArguments

train_args = TrainingArguments(
    output_dir="my_imdb_model", num_train_epochs=2,
    per_device_train_batch_size=128, per_device_eval_batch_size=128,
    eval_strategy="epoch", logging_strategy="epoch", save_strategy="epoch",
    load_best_model_at_end=True, metric_for_best_model="accuracy",
    report_to="none")

In [50]:
# the Trainer model: give it the model and the traning arguments!
from transformers import DataCollatorWithPadding, Trainer

trainer = Trainer(
    bert_for_binary_clf, train_args, train_dataset=tok_imdb_train_set,
    eval_dataset=tok_imdb_valid_set, compute_metrics=compute_accuracy,
    data_collator=DataCollatorWithPadding(bert_tokenizer))
train_output = trainer.train()

Epoch,Training Loss,Validation Loss,Accuracy
1,1.436077,nan,0.489000
2,0.000000,nan,0.489000


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.atte

### Hugging Face Pipelines
Premade models!

In [51]:
from transformers import pipeline

# if we don't specify a model, the pipeline() function will download
# the default model for the chosen task!

model_name = "distilbert-base-uncased-finetuned-sst-2-english"
classifier_imdb = pipeline("sentiment-analysis", model=model_name,
                           truncation=True, max_length=512)


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [52]:
classifier_imdb(train_reviews[:10])

[{'label': 'NEGATIVE', 'score': 0.9866334199905396},
 {'label': 'POSITIVE', 'score': 0.9916205406188965},
 {'label': 'POSITIVE', 'score': 0.9177579879760742},
 {'label': 'POSITIVE', 'score': 0.9998210072517395},
 {'label': 'NEGATIVE', 'score': 0.9997406601905823},
 {'label': 'POSITIVE', 'score': 0.9995219707489014},
 {'label': 'NEGATIVE', 'score': 0.999092698097229},
 {'label': 'NEGATIVE', 'score': 0.5279340147972107},
 {'label': 'NEGATIVE', 'score': 0.6894551515579224},
 {'label': 'NEGATIVE', 'score': 0.9993777275085449}]

In [53]:
review = ["Very nice movie"]
classifier_imdb(review)

[{'label': 'POSITIVE', 'score': 0.9998582601547241}]

In [54]:
# Bias and fairness:
s1 = ["I am from the USA"]
s2 = ["I am from Iraq"]
s3 = ["I am from Switzerland"]
classifier_imdb(s1+s2+s3)

[{'label': 'POSITIVE', 'score': 0.9642282128334045},
 {'label': 'NEGATIVE', 'score': 0.9706069231033325},
 {'label': 'POSITIVE', 'score': 0.9804428219795227}]