<a href="https://colab.research.google.com/github/tommypolpo/geron-hands_on_ML/blob/main/ch14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Shakespeare Training Dataset

In [8]:
from pathlib import Path
import urllib.request

def download_shkespeare_text():
  path = Path("datasets/shakespeare/shakespeare.txt")
  if not path.is_file():
    path.parent.mkdir(parents=True, exist_ok=True)
    url = "https://homl.info/shakespeare"
    urllib.request.urlretrieve(url, path)
  return path.read_text()

shakespeare_text = download_shkespeare_text()


In [9]:
print(shakespeare_text[:80])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.


In [10]:
len(shakespeare_text)

1115394

In [11]:
type(shakespeare_text)

str

In [12]:
# find the characters used in the text
vocab = sorted(set(shakespeare_text.lower()))
print(vocab)

['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [13]:
"".join(vocab) # this is just to visualize them "closer together"

"\n !$&',-.3:;?abcdefghijklmnopqrstuvwxyz"

In [14]:
# We now create the two translation dictionaries
char_to_id = {char:index for index, char in enumerate(vocab)}
id_to_char = {index:char for index, char in enumerate(vocab)}


In [15]:
# two helper functions to encode text to tensors of token IDs
import torch

def encode_text(text):
  return torch.tensor([char_to_id[char] for char in text.lower()])

def decode_text(char_ids):
  return "".join([id_to_char[char_id.item()] for char_id in char_ids])

In [16]:
encoded = encode_text("Hello, world!")
encoded


tensor([20, 17, 24, 24, 27,  6,  1, 35, 27, 30, 24, 16,  2])

In [17]:
decode_text(encoded)

'hello, world!'

### CharDataset Class

In [18]:
from torch.utils.data import Dataset, DataLoader

class CharDataset(Dataset):
  def __init__(self, text, window_length):
    self.encoded_text =  encode_text(text)
    self.window_length = window_length

  def __len__(self): # how many valids windows
    return len(self.encoded_text) - self.window_length

  # this takes an id as argument and returns the
  # corresponding training window and target (=window shifted by 1)
  def __getitem__(self, idx):
    if idx >= len(self):
      raise IndexError("dataset index out of range")
    end = idx + self.window_length
    window = self.encoded_text[idx:end]
    target = self.encoded_text[idx+1:end+1]
    return window, target

### DataLoaders

In [19]:
window_length = 50
batch_size = 64

train_set = CharDataset(shakespeare_text[:1_000_000], window_length)
valid_set = CharDataset(shakespeare_text[1_000_000:1_060_000], window_length)
test_set = CharDataset(shakespeare_text[1_060_000:], window_length)


train_loader = DataLoader(train_set, batch_size, shuffle=True)
valid_loader = DataLoader(valid_set, batch_size)
test_loader = DataLoader(test_set, batch_size)

##Evaluation and Training Functions

In [20]:
%pip install -q torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 24.4 MB/s eta 0:00:00


In [21]:
import torchmetrics

def evaluate_tm(model, data_loader, metric):
    model.eval()
    metric.reset()
    with torch.no_grad():
        for X_batch, y_batch in data_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            metric.update(y_pred, y_batch)
    return metric.compute()

def train(model, optimizer, loss_fn, metric, train_loader, valid_loader,
          n_epochs, patience=2, factor=0.5, epoch_callback=None):
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="max", patience=patience, factor=factor)
    history = {"train_losses": [], "train_metrics": [], "valid_metrics": []}
    for epoch in range(n_epochs):
        total_loss = 0.0
        metric.reset()
        model.train()
        if epoch_callback is not None:
            epoch_callback(model, epoch)
        for index, (X_batch, y_batch) in enumerate(train_loader):
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            loss = loss_fn(y_pred, y_batch)
            total_loss += loss.item()
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
            metric.update(y_pred, y_batch)
            train_metric = metric.compute().item()
            print(f"\rBatch {index + 1}/{len(train_loader)}", end="")
            print(f", loss={total_loss/(index+1):.4f}", end="")
            print(f", {train_metric=:.2%}", end="")
        history["train_losses"].append(total_loss / len(train_loader))
        history["train_metrics"].append(train_metric)
        val_metric = evaluate_tm(model, valid_loader, metric).item()
        history["valid_metrics"].append(val_metric)
        scheduler.step(val_metric)
        print(f"\rEpoch {epoch + 1}/{n_epochs},                      "
              f"train loss: {history['train_losses'][-1]:.4f}, "
              f"train metric: {history['train_metrics'][-1]:.2%}, "
              f"valid metric: {history['valid_metrics'][-1]:.2%}")
    return history

## Char-RNN Model

In [22]:
if torch.cuda.is_available():
  device = "cuda"
else:
  device = "cpu"

In [23]:
import torch.nn as nn
class ShakespeareModel(nn.Module):
    def __init__(self, vocab_size, n_layers=2, embed_dim=10, hidden_dim=128,
                 dropout=0.1):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, embed_dim)
        self.gru = nn.GRU(embed_dim, hidden_dim, num_layers=n_layers,
                          batch_first=True, dropout=dropout)
        self.output = nn.Linear(hidden_dim, vocab_size)

    def forward(self, X):
        embeddings = self.embed(X)
        outputs, _states = self.gru(embeddings)
        return self.output(outputs).permute(0, 2, 1)

torch.manual_seed(42)
model = ShakespeareModel(len(vocab)).to(device)

### Training

In [24]:
n_epochs = 2
xentropy = nn.CrossEntropyLoss()
optimizer = torch.optim.NAdam(model.parameters())
accuracy = torchmetrics.Accuracy(task="multiclass",
                                 num_classes=len(vocab)).to(device)

history = train(model, optimizer, xentropy, accuracy, train_loader, valid_loader,
                n_epochs)

Epoch 1/2,                      train loss: 1.4403, train metric: 55.25%, valid metric: 54.50%
Epoch 2/2,                      train loss: 1.3637, train metric: 57.12%, valid metric: 54.56%


In [25]:
torch.save(model.state_dict(), "my_shakespeare_model.pt")

### Prediction

In [26]:
model.eval()
text = "To be or not to b"
encoded_text = encode_text(text).unsqueeze(dim=0).to(device) # so now it has shape [1,18]

with torch.no_grad():
  Y_logits = model(encoded_text)
  predicted_char_id = Y_logits[0, :, -1].argmax().item() #largest logit of the last prediction: the next letter
  predicted_char = id_to_char[predicted_char_id]
  print(predicted_char) # correctly predict "e"!

e


## Fake Shakesperean Text

In [27]:
# how to use the torch.multinomial function to sample indices
torch.manual_seed(42)
probs = torch.tensor([[0.5, 0.4, 0.1]])
samples = torch.multinomial(probs, replacement = True, num_samples =10)
# replacement = True : allows the same index to be sampled more than once
samples

tensor([[0, 0, 0, 0, 1, 0, 2, 2, 0, 0]])

### Next Char function

In [28]:
import torch.nn.functional as F

# this function samples the character after "text" according to the probability
# predicted by the model (instead of argmax)
def next_char(model, text, temperature = 1):
  encoded_text = encode_text(text).unsqueeze(dim=0).to(device)
  with torch.no_grad():
    Y_logits = model(encoded_text)
    Y_probas= F.softmax(Y_logits[0,:,-1] / temperature, dim =-1)
    predicted_char_id = torch.multinomial(Y_probas, num_samples = 1).item()
    return id_to_char[predicted_char_id]


In [29]:
# this function repeatedly calls next_char

def extend_text(model, text, n_chars=300, temperature =1):
  for _ in range(n_chars):
    text += next_char(model, text, temperature)
  return text

In [30]:
# we can now generate text!

print(extend_text(model, "Ciao", temperature = 100))

Ciaojf3h :c;rjxfndp'cdt-!f
'eyouw xr3dozdcu,xy:utgj,p!hyzdkpxep-nas3fklr,oec3cbmieitp$yacd.r3pgauypj.wgitcea;,qk?tj
jr.$peixhk&bnecf;'onifi'&ytsy&3u.hdhfm
,dzmovfe:mhf:my:r,k;s-h cqvvnfnfsut&-oq'ryoeen?x-hp:d,y&wv f3,dzrdzj-p$lv?xpzh,fborp;'?$u;-dd?f-vkinst$;gd$bdg:on-;!wop;w- oechr?no$tenv;-o$;uqo
r:$l


## Sentiment Analysis: IMDB

### IMDB dataset

In [31]:
# see my bear note on how to Huuging Facce dataset library
from datasets import load_dataset

imbd_dataset = load_dataset("stanfordnlp/imdb")
split = imbd_dataset["train"].train_test_split(train_size=0.8)

imdb_train_set, imdb_valid_set = split["train"], split["test"]
imdb_test_set = imbd_dataset["test"]


README.md:   0%|          | 0.00/7.81k [00:00<?, ?B/s]

plain_text/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 21.0MB            

plain_text/train-00000-of-00001.parquet: downloading bytes:           |  0.00B            

plain_text/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 20.5MB            

plain_text/test-00000-of-00001.parquet: downloading bytes:           |  0.00B            

plain_text/unsupervised-00000-of-00001.p(…): reconstructing file:   0%|          |  0.00B / 42.0MB            

plain_text/unsupervised-00000-of-00001.p(…): downloading bytes:           |  0.00B            

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

In [32]:
imdb_train_set[1]["text"] #different from Geron's book

'A surprisingly good movie! It has quite a few good jokes thru out the whole movie. The only negative thing is that some scenes go to the extremes to show just how stupid the two main characters are. We get it, stupid blondes, get on with it! <br /><br />The plot just barely dodges being called "corny". And boobies are always a plus altho the movie for some strange reason doesn\'t play with that card very much even tho the plot line introduces two black haired women who act as the evil counter part of our two blondes.<br /><br />So all in all, a good movie to watch. I almost gave it an 8/10, but let\'s not get crazy.'

In [33]:
imdb_train_set[1]["label"]

1

### Tokenizer based on the BPE model

In [34]:
import tokenizers

bpe_model = tokenizers.models.BPE(unk_token="<unk>")
bpe_tokenizer = tokenizers.Tokenizer(bpe_model) #create a tokenizer based on the BPE model
bpe_tokenizer.pre_tokenizer = tokenizers.pre_tokenizers.Whitespace()
special_tokens = ["<pad>", "<unk>"]
bpe_trainer = tokenizers.trainers.BpeTrainer(vocab_size=1000,
                                             special_tokens=special_tokens)

#create a list of all the text in the IMDB dataset
train_reviews = [review["text"].lower() for review in imdb_train_set]

#train the tokenizer on this list
bpe_tokenizer.train_from_iterator(train_reviews, bpe_trainer)


In [35]:
# let us tokenize some text
some_review = "the movies was great and awesome! 😊"
bpe_encoding = bpe_tokenizer.encode(some_review)
bpe_encoding


Encoding(num_tokens=10, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])

In [36]:
bpe_encoding.tokens

['the', 'movies', 'was', 'great', 'and', 'aw', 'es', 'ome', '!', '<unk>']

In [37]:
bpe_token_ids = bpe_encoding.ids
bpe_token_ids

[138, 466, 192, 405, 153, 373, 149, 224, 3, 1]

In [38]:
bpe_tokenizer.decode(bpe_token_ids)


'the movies was great and aw es ome !'

In [39]:
# to create a single tensor containing all the tokens of multiple reviews
# they must be all of the same length: max_lenght + padding
bpe_tokenizer.enable_padding(pad_id=0, pad_token="<pad>")
bpe_tokenizer.enable_truncation(max_length=500)

In [40]:
# we encode 3 reviews at once:
bpe_encodings = bpe_tokenizer.encode_batch(train_reviews[:3])
bpe_batch_ids = torch.tensor([encoding.ids for encoding in bpe_encodings])
bpe_batch_ids

tensor([[ 49,  43, 357,  ...,   0,   0,   0],
        [ 41, 560, 909,  ...,   0,   0,   0],
        [183,  42, 193,  ..., 374,  59, 415]])

In [41]:
# attention mask tells us where there is no padding
attention_mask = torch.tensor([encoding.attention_mask for encoding in bpe_encodings])
attention_mask

tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1]])

In [42]:
lengths = attention_mask.sum(dim=-1)
lengths

tensor([203, 188, 500])

### Pretrained Tokenizers

#### GPT2 tokenizer

In [43]:
# Let's dowload the pretrained BBPE tokenizer used by the GPT-2 model
import transformers

gpt2_tokenizer = transformers.AutoTokenizer.from_pretrained("gpt2")

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [44]:
gpt2_encoding = gpt2_tokenizer(train_reviews[:3], truncation=True, max_length=500)

gpt2_token_ids = gpt2_encoding["input_ids"][0][:10]
gpt2_token_ids

[72, 1625, 1973, 428, 2646, 416, 5778, 618, 13487, 477]

In [45]:
gpt2_tokenizer.decode(gpt2_token_ids)

'i came across this film by accident when listing all'

#### WordPiece / BERT tokenizer

In [46]:
bert_tokenizer = transformers.AutoTokenizer.from_pretrained("bert-base-uncased")

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

### Train a Sentiment Analysis Model

#### DataLoader + Tokenization

In [47]:
# we pass a function to the DataLoader that tokenize, truncate and pad the reviews

def collate_fn(batch, tokenizer = bert_tokenizer):
  reviews = [review["text"] for review in batch]
  labels = [[review["label"]] for review in batch]

  encodings = tokenizer(reviews, padding = True, truncation=True, max_length=200,
                        return_tensors="pt")
  labels = torch.tensor(labels, dtype=torch.float32)
  return encodings, labels

In [48]:
batch_size = 256
imdb_train_loader = DataLoader(imdb_train_set, batch_size=batch_size, collate_fn=collate_fn, shuffle=True)
imdb_valid_loader = DataLoader(imdb_valid_set, batch_size=batch_size, collate_fn=collate_fn)
imdb_test_loader = DataLoader(imdb_test_set, batch_size=batch_size, collate_fn=collate_fn)

#### Sentiment Analysis Model

In [49]:
class SentimentAnalysisModel(nn.Module):
    def __init__(self, vocab_size, n_layers=2, embed_dim=128, hidden_dim=64,
                 pad_id=0, dropout=0.2):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, embed_dim,
                                  padding_idx=pad_id)
        self.gru = nn.GRU(embed_dim, hidden_dim, num_layers=n_layers,
                          batch_first=True, dropout=dropout)
        self.output = nn.Linear(hidden_dim, 1)

    def forward(self, encodings):
        embeddings = self.embed(encodings["input_ids"])
        _outputs, hidden_states = self.gru(embeddings)
        return self.output(hidden_states[-1])

In [50]:
torch.manual_seed(42)

vocab_size = bert_tokenizer.vocab_size # how many different tokens!
imdb_model_ps = SentimentAnalysisModel(vocab_size).to(device)

n_epochs = 5
xentropy = nn.BCEWithLogitsLoss()
optimizer = torch.optim.NAdam(imdb_model_ps.parameters())
accuracy = torchmetrics.Accuracy(task="binary").to(device)

history = train(imdb_model_ps, optimizer, xentropy, accuracy,
                imdb_train_loader, imdb_valid_loader, n_epochs)

Epoch 1/5,                      train loss: 0.6883, train metric: 53.11%, valid metric: 54.88%
Epoch 2/5,                      train loss: 0.6597, train metric: 61.32%, valid metric: 62.60%
Epoch 3/5,                      train loss: 0.5847, train metric: 69.52%, valid metric: 60.14%
Epoch 4/5,                      train loss: 0.4261, train metric: 81.39%, valid metric: 76.44%
Epoch 5/5,                      train loss: 0.3101, train metric: 87.62%, valid metric: 78.10%


#### Bidirectional model

In [55]:
class SentimentAnalysisModelBidi(nn.Module):
    def __init__(self, vocab_size, n_layers=2, embed_dim=128,
                 hidden_dim=64, pad_id=0, dropout=0.2):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, embed_dim,
                                  padding_idx=pad_id)
        self.gru = nn.GRU(embed_dim, hidden_dim, num_layers=n_layers,
                          batch_first=True, dropout=dropout, bidirectional=True)  # set bidirectional = true
        self.output = nn.Linear(2 * hidden_dim, 1)                               # the output dimension is now doubles

    def forward(self, encodings):
        embeddings = self.embed(encodings["input_ids"])
        #lengths = encodings["attention_mask"].sum(dim=1)
        #packed = pack_padded_sequence(embeddings, lengths=lengths.cpu(),
        #                              batch_first=True, enforce_sorted=False)
        _outputs, hidden_states = self.gru(embeddings)
        # we now need to concatenate the the forard output and backward output
        # of the GRU layer, before feeding it to the output layer
        n_dims = self.output.in_features
        top_states = hidden_states[-2:].permute(1, 0, 2).reshape(-1, n_dims)
        # and finally feed it to the output linear layer
        return self.output(top_states)

In [59]:
torch.manual_seed(42)

vocab_size = bert_tokenizer.vocab_size
imdb_model_bidi = SentimentAnalysisModelBidi(vocab_size).to(device)

n_epochs = 2
xentropy = nn.BCEWithLogitsLoss()
optimizer = torch.optim.NAdam(imdb_model_bidi.parameters())
accuracy = torchmetrics.Accuracy(task="binary").to(device)

history = train(imdb_model_bidi, optimizer, xentropy, accuracy, imdb_train_loader,
                imdb_valid_loader, n_epochs)

Epoch 1/2,                      train loss: 0.6668, train metric: 58.71%, valid metric: 67.06%
Epoch 2/2,                      train loss: 0.5372, train metric: 73.34%, valid metric: 74.62%


#### Pretrained Embeddings

In [60]:
# Download the pretrained BERT embedding layer
bert_model = transformers.AutoModel.from_pretrained("bert-base-uncased")
bert_model.embeddings.word_embeddings

model.safetensors: reconstructing file:   0%|          |  0.00B /  440MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


Embedding(30522, 768, padding_idx=0)

In [67]:
# instead of replacing our nn.Embedding layer, we inizialize it with the weights
# of the pretrained embedding layer
# the code is exactly the same except for the initialization of the embedding layer
# freeze = True for the first few epochs, then unfreeze to fine-tune the parameteres
class SentimentAnalysisModelPreEmbeds(nn.Module):
    def __init__(self, pretrained_embeddings, n_layers=2, embed_dim=128,
                 hidden_dim=64, pad_id=0, dropout=0.2):
        super().__init__()
        ##### Embedding layer
        weights = pretrained_embeddings.weight.data
        self.embed = nn.Embedding.from_pretrained(weights, freeze=True)
        embed_dim = weights.shape[-1]
        #####
        self.gru = nn.GRU(embed_dim, hidden_dim, num_layers=n_layers,
                          batch_first=True, dropout=dropout, bidirectional=True)  # set bidirectional = true
        self.output = nn.Linear(2 * hidden_dim, 1)                               # the output dimension is now doubles

    def forward(self, encodings):
        embeddings = self.embed(encodings["input_ids"])
        #lengths = encodings["attention_mask"].sum(dim=1)
        #packed = pack_padded_sequence(embeddings, lengths=lengths.cpu(),
        #                              batch_first=True, enforce_sorted=False)
        _outputs, hidden_states = self.gru(embeddings)
        # we now need to concatenate the the forard output and backward output
        # of the GRU layer, before feeding it to the output layer
        n_dims = self.output.in_features
        top_states = hidden_states[-2:].permute(1, 0, 2).reshape(-1, n_dims)
        # and finally feed it to the output linear layer
        return self.output(top_states)

In [68]:
torch.manual_seed(42)

imdb_model_bert_embeds = SentimentAnalysisModelPreEmbeds(
    bert_model.embeddings.word_embeddings).to(device)

n_epochs = 3
xentropy = nn.BCEWithLogitsLoss()
optimizer = torch.optim.NAdam(imdb_model_bert_embeds.parameters())
accuracy = torchmetrics.Accuracy(task="binary").to(device)

history = train(imdb_model_bert_embeds, optimizer, xentropy, accuracy,
                imdb_train_loader, imdb_valid_loader, n_epochs)

Epoch 1/3,                      train loss: 0.6865, train metric: 54.77%, valid metric: 62.74%
Epoch 2/3,                      train loss: 0.6572, train metric: 60.94%, valid metric: 64.52%
Epoch 3/3,                      train loss: 0.5889, train metric: 69.26%, valid metric: 76.32%
